version: "3.9"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:latest
    container_name: redis-server
    command: ["redis-server", "--requirepass", "Rakshas&$ASURA_42589"]
    ports:
      - "6379:6379"
