"""add mask_available column

Revision ID: 06798a203cb0
Revises: 34f6d1209d7e
Create Date: 2025-09-05 09:08:54.751010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06798a203cb0'
down_revision: Union[str, Sequence[str], None] = '34f6d1209d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_models', sa.Column('mask_available', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('phone_models', 's3_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_models', sa.Column('s3_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('phone_models', 'mask_available')
    # ### end Alembic commands ###
